steps:
  - name: "python:3.11"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv --user && python -m uv sync
        
  - name: "python:3.11"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        python -m uv run app/agent_engine_app.py
    env:
    - 'PROJECT_ID=$_PROD_PROJECT_ID'
    - 'LOCATION=$_REGION'

substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: us-central1
options:
  logging: CLOUD_LOGGING_ONLY
